-- ========================================================================
-- DOUBLE 7 LOGISTICS • COMPLETE PRODUCTION DATABASE SCHEMA
-- Cloudflare D1 (SQLite) / Local SQLite Database Definition
-- ========================================================================

-- ------------------------------------------------------------------------
-- 1. SHIPMENTS & CONSIGNMENTS TABLE
-- Core table storing bookings, parcels, manifests, and logistics telemetry.
-- Supports standard waybills, bulk Excel uploads, COD values, and tracking.
-- ------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS shipments (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  tracking_number TEXT UNIQUE,
  booking_no TEXT UNIQUE,
  parcel_no TEXT,
  reference_number TEXT,
  reference_no TEXT,
  status TEXT DEFAULT 'Booked',
  origin TEXT DEFAULT 'Kathmandu Hub',
  destination TEXT,
  merchant TEXT,
  sender_name TEXT,
  sender_phone TEXT,
  recipient_name TEXT,
  consignee_name TEXT,
  consignee_phone TEXT,
  consignee_email TEXT,
  consignee_address TEXT,
  city TEXT,
  province TEXT,
  postal_code TEXT,
  country TEXT DEFAULT 'Nepal',
  cargo_description TEXT,
  weight_kg REAL DEFAULT 0,
  pieces INTEGER DEFAULT 1,
  service_type TEXT DEFAULT 'Express Courier',
  cod_amount REAL DEFAULT 0,
  remarks TEXT,
  raw_details TEXT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Performance Indexes for Shipments Table
CREATE INDEX IF NOT EXISTS idx_shipments_booking ON shipments(booking_no);
CREATE INDEX IF NOT EXISTS idx_shipments_parcel ON shipments(parcel_no);
CREATE INDEX IF NOT EXISTS idx_shipments_tracking ON shipments(tracking_number);
CREATE INDEX IF NOT EXISTS idx_shipments_phone ON shipments(consignee_phone);
CREATE INDEX IF NOT EXISTS idx_shipments_merchant ON shipments(merchant);
CREATE INDEX IF NOT EXISTS idx_shipments_status ON shipments(status);
CREATE INDEX IF NOT EXISTS idx_shipments_created ON shipments(created_at);

-- ------------------------------------------------------------------------
-- 2. TRACKING EVENTS / CHECKPOINTS TABLE
-- Records scan events, hub transit logs, status transitions, and timestamps.
-- ------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS tracking_events (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  shipment_id TEXT NOT NULL,
  status TEXT NOT NULL,
  location TEXT,
  remarks TEXT,
  event_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_events_shipment ON tracking_events(shipment_id);
CREATE INDEX IF NOT EXISTS idx_events_time ON tracking_events(event_time);

-- ------------------------------------------------------------------------
-- 3. BRANCH MANIFESTS TABLE
-- Linehaul dispatch manifests generated by branch hubs for transport.
-- ------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS branch_manifests (
  id TEXT PRIMARY KEY,
  manifest_number TEXT UNIQUE NOT NULL,
  branch_origin TEXT NOT NULL,
  branch_code TEXT NOT NULL,
  destination_hub TEXT NOT NULL,
  destination_city TEXT NOT NULL,
  linehaul_vehicle TEXT,
  driver_name TEXT,
  driver_phone TEXT,
  seal_number TEXT,
  items_json TEXT,
  total_shipments INTEGER DEFAULT 0,
  total_pieces INTEGER DEFAULT 0,
  total_weight_kg REAL DEFAULT 0,
  total_cod_npr REAL DEFAULT 0,
  status TEXT DEFAULT 'Draft',
  notes TEXT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  generated_at TIMESTAMP,
  printed_at TIMESTAMP,
  dispatched_at TIMESTAMP,
  dispatched_by TEXT
);

CREATE INDEX IF NOT EXISTS idx_manifest_branch ON branch_manifests(branch_code);
CREATE INDEX IF NOT EXISTS idx_manifest_status ON branch_manifests(status);

-- ------------------------------------------------------------------------
-- 4. CASH-ON-DELIVERY (COD) RECORDS TABLE
-- Tracks lifecycle of cash collected by riders, hub remittance, and payout.
-- ------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS cod_records (
  id TEXT PRIMARY KEY,
  consignment_id TEXT NOT NULL,
  tracking_number TEXT,
  merchant_id TEXT NOT NULL,
  merchant_name TEXT,
  consignee_name TEXT,
  consignee_phone TEXT,
  destination_city TEXT,
  destination_hub TEXT,
  rider_name TEXT,
  order_amount_npr REAL DEFAULT 0,
  collected_amount_npr REAL DEFAULT 0,
  remitted_amount_npr REAL DEFAULT 0,
  stage TEXT DEFAULT 'order_placed',
  status TEXT DEFAULT 'pending',
  is_discrepancy INTEGER DEFAULT 0,
  discrepancy_npr REAL DEFAULT 0,
  discrepancy_reason TEXT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_cod_merchant ON cod_records(merchant_id);
CREATE INDEX IF NOT EXISTS idx_cod_tracking ON cod_records(tracking_number);
CREATE INDEX IF NOT EXISTS idx_cod_stage ON cod_records(stage);

-- ------------------------------------------------------------------------
-- 5. MERCHANT PAYOUT REQUESTS TABLE
-- Remittance withdrawal requests from merchants to their bank accounts.
-- ------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS payout_requests (
  id TEXT PRIMARY KEY,
  merchant_id TEXT NOT NULL,
  merchant_name TEXT,
  email TEXT,
  amount REAL DEFAULT 0,
  bank_name TEXT,
  account_no TEXT,
  branch TEXT,
  status TEXT DEFAULT 'pending',
  requested_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  settled_at TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_payout_merchant ON payout_requests(merchant_id);
CREATE INDEX IF NOT EXISTS idx_payout_status ON payout_requests(status);

-- ------------------------------------------------------------------------
-- 6. WAITLIST SUBSCRIBERS TABLE
-- Public landing page waitlist registrations.
-- ------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS waitlist_subscribers (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  email TEXT UNIQUE NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- ------------------------------------------------------------------------
-- 7. USERS & ACCESS CONTROL TABLE (USERS_DB)
-- Super Admins, Branch Controllers, Ops Managers, and Registered Merchants.
-- ------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS users (
  id TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  email TEXT UNIQUE NOT NULL,
  role TEXT DEFAULT 'merchant',
  sub_role TEXT,
  company TEXT,
  phone TEXT,
  status TEXT DEFAULT 'active',
  cod_balance_npr REAL DEFAULT 0,
  password TEXT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_users_email ON users(email);
CREATE INDEX IF NOT EXISTS idx_users_role ON users(role);

-- ------------------------------------------------------------------------
-- 8. SUB-USERS & TEAM MEMBERS TABLE (USERS_DB)
-- Staff accounts operating under a primary merchant or admin account.
-- ------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS sub_users (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  parent_id TEXT NOT NULL,
  email TEXT UNIQUE NOT NULL,
  name TEXT NOT NULL,
  role TEXT DEFAULT 'merchant',
  password_hash TEXT,
  permissions TEXT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_sub_users_parent ON sub_users(parent_id);
